#  docker-compose up --build -d
version: '3.3'

services:
  #  echo-api:
  #    build:
  #      context: .
  #    container_name: echo-api
  #    volumes:
  #      - ./api:/var/www/html
  #    networks:
  #      - echo-network
  #    depends_on:
  #      - php
  #    environment:
  #      - APP_ENV=local
  #
  #  echo-api-queue:
  #    build:
  #      context: .
  #    container_name: echo-api-queue
  #    command: supervisord -c /etc/supervisord.conf
  #    volumes:
  #      - ./config/supervisor/supervisord.conf:/etc/supervisord.conf
  #      - ./api:/var/www/html
  #    networks:
  #      - echo-network
  #    depends_on:
  #      - php

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config/nginx/conf.d/front.conf:/etc/nginx/conf.d/front.conf
      - ./config/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api:/var/www/html
      - ./front:/var/www/dist
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - echo-network

  php:
    image: php:8.1-fpm
    container_name: php
    volumes:
      - ./api:/var/www/html
    networks:
      - echo-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - echo-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "19200:9200"
    networks:
      - echo-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123 #rootpassword
      MYSQL_DATABASE: echo
      MYSQL_USER: echo
      MYSQL_PASSWORD: echo@123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - echo-network

networks:
  echo-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
