#  docker-compose up --build -d
#  docker-compose build --no-cache && docker-compose up -d
services:
  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./api:/var/www/html
    networks:
      - echo-network

  echo-api:
    build:
      context: .
    container_name: echo-api
    volumes:
      - ./config/supervisor:/etc/supervisor
      - ./api:/var/www/html
    networks:
      - echo-network
    depends_on:
      - php
    environment:
      - APP_ENV=local

  echo-api-queue:
    build:
      context: .
    container_name: echo-api-queue
    command: supervisord -c /etc/supervisord.conf
    volumes:
      - ./config/supervisor:/etc/supervisor
      - ./api:/var/www/html
    networks:
      - echo-network
    depends_on:
      - php

  nginx-api:
    image: nginx:latest
    container_name: nginx-api
    volumes:
      - ./config/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - php
    networks:
      - echo-network

  nginx-front:
    image: nginx:latest
    container_name: nginx-front
    volumes:
      - ./config/nginx/conf.d/front.conf:/etc/nginx/conf.d/front.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./front:/var/www
    ports:
      - "9090:9090"
    depends_on:
      - php
    networks:
      - echo-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - echo-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "19200:9200"
    networks:
      - echo-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root@123 #rootpassword
      MYSQL_DATABASE: echo
      MYSQL_USER: echo
      MYSQL_PASSWORD: echo@123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - echo-network

networks:
  echo-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local